name: Build USVFS

on:
  push:
    branches: [master, dev/cmake]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    name: Build USVFS
    strategy:
      matrix:
        arch: [x86, x64]
        config: [Debug, Release]
    runs-on: windows-2022
    steps:
      # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      # checkout USVFS and vcpkg
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: f61a294e765b257926ae9e9d85f96468a0af74e7
          vcpkgJsonGlob: ${{ github.workspace }}/usvfs/vcpkg.json

      # configure
      - run: cmake --preset vs2022-windows-${{ matrix.arch }} -B build_${{ matrix.arch }}
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      # build
      - run: cmake --build build_${{ matrix.arch }} --config ${{ matrix.config }}
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - if: matrix.config == 'Debug'
        uses: actions/upload-artifact@master
        with:
          name: usvfs-libs_${{ matrix.arch }}
          path: ./lib
      - if: matrix.config == 'Debug'
        uses: actions/upload-artifact@master
        with:
          name: usvfs-bins_${{ matrix.arch }}
          path: ./bin
      - if: matrix.config == 'Debug'
        uses: actions/upload-artifact@master
        with:
          name: usvfs-tests_${{ matrix.arch }}
          path: ./test/bin

  # merge x86 / x64 artifacts
  merge-artifacts:
    runs-on: ubuntu-latest
    name: Merge Artifacts for Tests
    needs: build
    steps:
      - name: Merge USVFS libs
        uses: actions/upload-artifact/merge@v4
        with:
          name: usvfs-libs
          pattern: usvfs-libs_*
      - name: Merge USVFS bins
        uses: actions/upload-artifact/merge@v4
        with:
          name: usvfs-bins
          pattern: usvfs-bins_*
      - name: Merge USVFS tests
        uses: actions/upload-artifact/merge@v4
        with:
          name: usvfs-tests
          pattern: usvfs-tests_*

  test:
    name: Test USVFS
    needs: merge-artifacts
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: usvfs-libs
          path: ./lib
      - uses: actions/download-artifact@master
        with:
          name: usvfs-bins
          path: ./bin
      - uses: actions/download-artifact@master
        with:
          name: usvfs-tests
          path: ./test/bin
      - run: ./test/bin/shared_test_${{ matrix.arch }}.exe
        if: always()
      - run: ./test/bin/testinject_bin_${{ matrix.arch }}.exe
        if: always()
      - run: ./test/bin/thooklib_test_${{ matrix.arch }}.exe
        if: always()
      - run: ./test/bin/tinjectlib_test_${{ matrix.arch }}.exe
        if: always()
      - run: ./test/bin/tvfs_test_${{ matrix.arch }}.exe
        if: always()
      - run: ./test/bin/usvfs_test_runner_${{ matrix.arch }}.exe
        if: always()
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: tests-outputs_${{ matrix.arch }}
          path: ./test/temp
          if-no-files-found: ignore
          retention-days: 7
          overwrite: true
